# Generated by Django 5.2.6 on 2025-10-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=20)),
                ('cSex', models.CharField(default='F', max_length=1)),
                ('cBirthday', models.DateField(blank=True, null=True)),
                ('cEmail', models.CharField(max_length=100)),
                ('cPhone', models.CharField(max_length=50)),
                ('cAddr', models.CharField(max_length=255)),
            ],
        ),
    ]
